import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

export const collections = {
	// Andy-style atomic notes collection (notes-only site)
	notes: defineCollection({
		loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/notes' }),
		schema: z.object({
			title: z.string(),
			// Privacy by default
			visibility: z.enum(['public', 'private', 'draft']).default('private'),
			// Note status (plain English, not digital garden jargon)
			status: z.enum(['draft', 'live', 'updated']).default('draft'),
			// Tags for related notes
			tags: z.array(z.string()).default([]),
			// Aliases for WikiLink resolution
			aliases: z.array(z.string()).default([]),
			// First published date (yyyy-mm-dd) - for SEO and publish date display
			created: z.union([z.string(), z.date()]).transform(val =>
				val instanceof Date ? val.toISOString().split('T')[0] : val
			).optional(),
			// Last updated (yyyy-mm-dd) - coerce dates to strings
			updated: z.union([z.string(), z.date()]).transform(val =>
				val instanceof Date ? val.toISOString().split('T')[0] : val
			).optional(),
			// Author (for schema.org structured data)
			author: z.string().default('Your Name'),
			// Short summary for previews
			summary: z.string().optional(),
		}),
	}),
	// Deep research reports (long-form, separate from atomic notes)
	research: defineCollection({
		loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/research' }),
		schema: z.object({
			title: z.string(),
			author: z.string().default('Your Name'),
			// Link to the summary note slug (e.g., "research-oss-business-models")
			summaryNote: z.string(),
			// ISO date strings for timestamps
			created: z.union([z.string(), z.date()]).transform(val =>
				val instanceof Date ? val.toISOString().split('T')[0] : val
			),
			updated: z.union([z.string(), z.date()]).transform(val =>
				val instanceof Date ? val.toISOString().split('T')[0] : val
			).optional(),
			// Research metadata
			wordCount: z.number(),
			model: z.string().default('Claude Sonnet 3.5'),
			aiSource: z.string().default('Claude Code'),
			// Context for info box (can contain wikilinks)
			context: z.string(),
			// Short description for SEO
			summary: z.string().optional(),
		}),
	}),
	// Standalone editorial pages that live outside /notes/ and /research/.
	// Registering them here makes their route metadata available to search and WikiLinks.
	pages: defineCollection({
		loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/pages' }),
		schema: z.object({
			title: z.string(),
			// Canonical route this page renders at, e.g. "/about/". Must be absolute
			// with a trailing slash so it matches the graph's canonical URL form.
			url: z.string().regex(/^\/.+\/$/),
			summary: z.string(),
			aliases: z.array(z.string()).default([]),
			tags: z.array(z.string()).default([]),
			created: z.union([z.string(), z.date()]).transform(val =>
				val instanceof Date ? val.toISOString().split('T')[0] : val
			).optional(),
			updated: z.union([z.string(), z.date()]).transform(val =>
				val instanceof Date ? val.toISOString().split('T')[0] : val
			).optional(),
		}),
	}),
	// Daily/weekly changelog updates (meta-content about wiki changes)
	updates: defineCollection({
		loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/updates' }),
		schema: z.object({
			title: z.string(),
			// ISO date for the update (yyyy-mm-dd)
			date: z.union([z.string(), z.date()]).transform(val =>
				val instanceof Date ? val.toISOString().split('T')[0] : val
			),
			// One-liner for homepage card
			summary: z.string(),
			// Whether this was generated by AI (future agent use)
			aiGenerated: z.boolean().default(false),
			// The pages this update rolls up. Titles or site paths — both resolve,
			// and both count as edges in the graph, so an update is linked to the
			// writing it describes.
			links: z.array(z.string()).default([]),
			// Author
			author: z.string().default('Your Name'),
		}),
	}),
};

